server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /app/ {
        alias /usr/share/nginx/html/app/;
        try_files $uri $uri/ /app/index.html;
    }

    location / {
        return 301 /app/;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
